apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  namespace: kubelite
spec:
  type: ClusterIP
  selector:
    app: calculator-service
  ports:
    - port: 5000
      targetPort: 5000
